AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda function that moves data from AWS IoT Core to AWS Dynamo DB

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 60
    Layers:
      - arn:aws:lambda:eu-north-1:580510132728:layer:GeohashingLayer:7
      - arn:aws:lambda:eu-north-1:580510132728:layer:RandomStringLayer:1

Resources:
  IoTCoreToDynamoDbFunction2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IoTCoreToDynamoDb2
      CodeUri: .
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NimTrack2
      Events:
        IoTCoreToDynamoDb2:
          Type: IoTRule
          Properties:
            Sql: "SELECT * FROM 'esp32/josiah1'"
            AwsIotSqlVersion: "2016-03-23"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "aws-sdk"
          - "geohashing"
          - "randomstring"

  NimTrack2:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
